import{useState}from'react';import{Bell,Box,Check,ChevronRight,Gift,Heart,Home,MapPin,Navigation,ScanLine,Search,ShieldCheck,X}from'lucide-react';
const campaigns=[{title:'Gambella Flood Relief',place:'Gambella Region',raised:3750000,goal:5000000,pct:75,days:4,color:'#2874c6',icon:'🌊'},{title:'Borena Drought Response',place:'Oromia Region',raised:1280000,goal:3000000,pct:43,days:9,color:'#d47c26',icon:'☀️'}];
export default function App(){const[tab,setTab]=useState('home'),[campaign,setCampaign]=useState(null),[amount,setAmount]=useState(200),[confirmed,setConfirmed]=useState(false),[scan,setScan]=useState(false);const pay=()=>{setCampaign(null);setConfirmed(true)};return <div className="app">
 <header><div className="mpesa"><span>M</span><div><b>Negarit Relief</b><small>Powered by M-PESA</small></div></div><button><Bell/><i/></button></header>
 <main>{tab==='home'&&<><section className="hero"><div><span>TOGETHER, WE RESPOND</span><h1>Give hope.<br/><em>Make an impact.</em></h1><p>100% transparent emergency relief, delivered to communities that need it most.</p></div><Heart/></section><div className="secure"><ShieldCheck/><span><b>Verified & secure giving</b><small>Every campaign is approved by Negarit agencies</small></span><Check/></div><div className="title"><div><h2>Active emergencies</h2><p>Your help is needed today</p></div><button>View all</button></div>{campaigns.map(c=><Campaign key={c.title} c={c} onDonate={()=>setCampaign(c)}/>)}</>}
 {tab==='boxes'&&<Boxes onScan={()=>setScan(true)}/>} {tab==='impact'&&<Impact/>}</main>
 <nav><button className={tab==='home'?'active':''} onClick={()=>setTab('home')}><Home/><span>Relief</span></button><button className={tab==='boxes'?'active':''} onClick={()=>setTab('boxes')}><MapPin/><span>Smart Boxes</span></button><button className={tab==='impact'?'active':''} onClick={()=>setTab('impact')}><Gift/><span>My Impact</span></button></nav>
 {campaign&&<div className="shade"><div className="sheet"><div className="grab"/><button className="close" onClick={()=>setCampaign(null)}><X/></button><small>DONATE TO</small><h2>{campaign.title}</h2><p>Choose a quick amount or enter your own.</p><div className="amounts">{[50,200,1000].map(a=><button className={amount===a?'active':''} onClick={()=>setAmount(a)} key={a}><b>{a}</b><span>ETB</span></button>)}</div><label className="custom">ETB <input type="number" value={amount} onChange={e=>setAmount(e.target.value)}/></label><button className="pay" onClick={pay}><span>M</span> Donate {amount} ETB with M-PESA <ChevronRight/></button><div className="pin-note"><ShieldCheck/>Your M-PESA PIN prompt will appear next</div></div></div>}
 {scan&&<Scanner close={()=>setScan(false)} success={()=>{setScan(false);setConfirmed(true)}}/>}
 {confirmed&&<div className="shade"><div className="confirm"><div className="success"><Check/></div><small>DONATION CONFIRMED</small><h2>You made a difference!</h2><p>Your donation is verified. A reward has been added to your Safaricom line.</p><div className="reward"><Gift/><span><small>YOU EARNED</small><b>50 MB data bundle</b></span></div><button className="pay" onClick={()=>setConfirmed(false)}>Done</button></div></div>}
 </div>}
function Campaign({c,onDonate}){return <article className="campaign"><div className="campaign-img" style={{background:`linear-gradient(120deg,${c.color}dd,${c.color}77)`}}><span>{c.icon}</span><label>URGENT</label><small>{c.days} days left</small></div><div className="campaign-body"><div className="place"><MapPin/>{c.place}</div><h3>{c.title}</h3><div className="stats"><b>{(c.raised/1000000).toFixed(2)}M ETB</b><span>of {(c.goal/1000000).toFixed(1)}M</span><strong>{c.pct}%</strong></div><div className="bar"><i style={{width:c.pct+'%',background:c.color}}/></div><div className="support"><span><i>AT</i><i>MK</i><i>+</i> 2,481 donors</span><button onClick={onDonate}>Donate now <ChevronRight/></button></div></div></article>}
function Boxes({onScan}){return <section className="page"><small>PHYSICAL DONATIONS</small><h1>Find a Smart Box</h1><p>Drop clothes, food, or essentials at a verified Safaricom outlet.</p><div className="map"><div className="roads"/><i className="pin p1">M</i><i className="pin p2">M</i><i className="pin p3">M</i><button><Navigation/></button></div><button className="scan" onClick={onScan}><ScanLine/><span><b>Scan a Smart Box QR</b><small>Verify your drop-off & earn a reward</small></span><ChevronRight/></button><h2>Nearest locations</h2>{[['Bole Medhanialem Safaricom','0.8 km'],['Mexico Square Retail Centre','2.4 km'],['Kazanchis M-PESA Centre','3.1 km']].map(x=><div className="location-row" key={x[0]}><MapPin/><span><b>{x[0]}</b><small>Open · Closes 6:00 PM</small></span><strong>{x[1]}</strong></div>)}</section>}
function Scanner({close,success}){return <div className="scanner"><button onClick={close}><X/></button><h3>Scan Smart Box</h3><p>Align the QR code inside the frame</p><div className="scan-frame"><span/><span/><span/><span/><i/></div><button className="simulate" onClick={success}>Simulate successful scan</button></div>}
function Impact(){return <section className="page"><small>YOUR CONTRIBUTIONS</small><h1>My impact</h1><div className="impact-card"><Gift/><small>TOTAL GIVEN</small><h2>1,250 ETB</h2><p>Across 3 emergency campaigns</p></div><div className="impact-grid"><div><b>150 MB</b><span>Rewards earned</span></div><div><b>2</b><span>Box drop-offs</span></div></div><h2>Recent activity</h2>{['Gambella Flood Relief','Smart Box · Bole','Borena Drought Response'].map((x,i)=><div className="location-row" key={x}><Check/><span><b>{x}</b><small>{i?'18 July 2026':'Today, 10:42'}</small></span><strong>{i===1?'Items':'200 ETB'}</strong></div>)}</section>}
